### ISSUE TITLE
Questions About Running DistGER on Flickr dataset

### ISSUE THREAD

**Issue by KYCoraxxx** [RocmFang/DistGER#1]
Hello, I've read your paper and I'm running DistGER on Flickr dataset.
I've downloaded the dataset from the [public source](http://datasets.syr.edu/datasets/Flickr.html) mentioned by your README. But it's consisted of four csv files. To make the partition process work. I simply substitute its comma with space, name edges.csv as fl-8.data, then name group-edges.csv as fl-8.test (I'm not sure about how to write the test data yet, and the number of groups is far less than the number of nodes, hence I directly use the group-edges.csv as test data) and run:
` ./bin/mpgp -i ../dataset/FL/fl-8.data -e ../dataset/FL/fl-8.test -v 80513 -p 1 -t 1`
it quickly gives me the error result as below but the log file records nothing:

> graph path: ../dataset/FL/fl-8.data
> v num: 80513
> read graph and cn finish
> convert_undirecteds finished
> count_degree finished
> Segmentation fault (core dumped)

I don't know how to deal with it, so I try to go on running the command:
`./bin/gconverter -i ../dataset/FL/fl-8.data -o ../dataset/FL/fl.data -s unweighted` 
the executing result "5899882 edges are converted" seems to be fine. 
But there is no .part file, so I use fl.part, which is the result of executing the graph embedding to fl-8.test file, as substitution (I do believe it's not right) , then I start the training process, it quickly gives the 139 exit code.
I think it's my process of converting csv file to the file format that mpgp can recognize, or the process of choosing test data have something wrong, but I don't know how to correct it, could you please help me with it?

**Comment by trsenli** [comment]
Hello, your substitution  is  proper, but the graph data still needs to meet another condition. In MPGP, we assume the vertex ID is the **continuous natural number** , as well as the option "v" (aka, vertex num) is the actual number of  individual vertex. The discontinuous vertex IDs are inconvenient for MPGP. 

Here is a graph data.
```txt
1  2 
2  4
```
We consider the number of vertices  to be  3 instead of 4 . And relabel the graph.
```txt
0  1
1  2
```
You could process data by yourself or use the provided relabeling tool at `./bin/relabel` .

---

Here's the  workflow from scratch.

Substitute comma with space.

`sed 's/,/ /g' edges.csv > edges.txt`

Preprocess the vertex ID. 

`./bin/relabel -i ./edges.txt -o ./flick.txt`

In the stdout, you could get the actual vertex num, 80078.
>eid: 3924672 max id: 80513
>relabel ok, start writing
>3933254 edges are relabeled 
>vertex num: 80078
>[relabel] time: 1.342909

Partition the graph by MPGP. 

`./bin/mpgp -i ./flick.txt -v 80078 -p 8` 

Generally, you would get two files.  `flick.txt-8-r` is the relabeled graph data(MPGP also relabels the graph) , and `flick.txt-8-r` records the partition. 

As for [-e]  ,aka  `test_edges`,  refers to the test set in  your downstream machine learning tasks. It will keep the vertex ID consistent after relabeling.

Then, `gconverter`  `flick.txt-8-r` into binary , run huge_walk  as described in `README`. 

---

I've  added some annotations for Tools in latest commit(70ae152). You could pull  and `mpgp -h` to check it.

Hope it could help you.

**Comment by KYCoraxxx** [comment]
Thanks a lot for your reply😆 , I've run the commands as you describe, the result of mpgp (without test data) goes like this:

> [start]2023-10-21 20:12:26
> graph path: ../dataset/flick.txt
> v num: 80078
> read graph and cn finish
> convert_undirecteds finished
> count_degree finished
> build csr finshed
> sort csr finshed
> stream mode: -DFS-degree
> stream size: 80069    99.99%
> Progress: 98.75%partition finished
> partition process
> relabel finished
> print finished
> [timer:runtime] 9.202285 s(0.006390 h)
> [end]2023-10-21 20:12:35
> [duration]0d 0h 0m 9s 

then I run the following command to start graph embedding:
`./bin/gconverter -i ../dataset/flick.txt-8-r -o ../dataset/flick-8.data-r -s unweighted`
the result is :

> 1966627 edges are converted

then the command to start huge_walk:
`mpiexec -n 8 ./bin/huge_walk -g ../dataset/flick-8.data-r -p ../dataset/flick-8.part -v 80078 -w 80078 -o ./out/walks.txt -eoutput ./out/flick-r_emb.txt -size 128 -iter 1 -threads 72 -window 10 -negative 5 -batch-size 21 -min-count 0 -sample 1e-3 -alpha 0.01 -debug 2`
But the process crashed with exit code 9, I was confused by this condition, it should not be the problem of memory, because the accessible memory of the server is more than 180GB, I've successfully run the LiveJournal dataset, and the latter should use more memory than Flickr, and it crashes just after finishing reading the graph data:

> read edge=========ok
> read edge=========ok
> read edge=========ok
> read edge=========ok
> read edge=========ok
> read edge=========ok
> read edge=========ok
> read edge=========ok
> 
> =   BAD TERMINATION OF ONE OF YOUR APPLICATION PROCESSES
> =   EXIT CODE: 9

I think it should be the problem of parameter and I've tried to adjust some parameter (command above with 80513 vertexes and walkers has also gained the exit code 9), but I'm not very sure about how to adjust or if it's the problem of parameter.😢
